In [2]:
# vectorization mean full array per operation  apply karo without loop 
import numpy as np
arr = np.array([1,2,3])
result = arr * 3
print(result)

[3 6 9]


In [3]:
arr = np.array([[1,2,3],[5,9,6]])
result = arr * 3
print(result)

[[ 3  6  9]
 [15 27 18]]


In [7]:
# without numpy
arr = [1,2,3]
result = []
for i in arr:
    result.append(i * 3)
print(result)
print(type(result))

[3, 6, 9]
<class 'list'>


In [9]:
# broadcasting mean Different shapes ke arrays ke darmiyan operation possible banana
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
result1 = arr + arr2
print(result1)
result2 = arr * arr2
print(result2)


[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]
