 ### Day 18 numpy labrary
  ## Today Concept
  1. boolean maskin
  2. filtering
  3. condition selection
  

In [1]:
# booleanmasking as ka matlab hai true ya false answer da na
import numpy as np
arr = np.array([1,2,3,9,4])
print(arr >= 4)


[False False False  True  True]


In [3]:
# filtering condition mean ka condition ko filer karna jo as condition ko full fill kara 
arr = np.array([1,2,3,9,4])
filter_values = arr[arr >= 4]
print(filter_values)

[9 4]


In [5]:
# conditional selection mean according to conditon value ko select karna 
arr = np.array([3,9])
result= np.where(arr >= 4, 'greater than 3','less than 4')
print(result)

['less than 4' 'greater than 3']


In [ ]:
# Student Marks Analysis

marks = np.array([35, 78, 45, 90, 28, 65, 82, 39])

# Boolean masking se find karo kaun se students ke marks 50 ya zyada hain.
print(marks >= 50)

# Filtering se sirf passing marks nikalo (passing marks = 50).
result = marks[marks >= 50]
print(result)

# 80 se zyada marks lene wale students find karo.
count = 0 
result = np.where(marks >= 80,'greater than 80','less than 80')
print(result)

[False  True False  True False  True  True False]
[78 90 65 82]
['less than 80' 'less than 80' 'less than 80' 'greater than 80'
 'less than 80' 'less than 80' 'greater than 80' 'less than 80']


In [10]:
# Weather Analysis

temperature = np.array([28, 35, 41, 22, 38, 19, 32])

# 35 se zyada temperatures filter karo.
high_tem = temperature[temperature > 35]
print(high_tem)
# 25 se kam temperatures find karo.
low_tem = temperature[temperature < 25]
print(low_tem)
# np.where() use karke 35 ya zyada ko "Hot" aur baqi ko "Normal" label do.
result = np.where(temperature >35, 'Hot','Normal')
print(result)

[41 38]
[22 19]
['Normal' 'Normal' 'Hot' 'Normal' 'Hot' 'Normal' 'Normal']


In [11]:
# Monthly Expenses

expenses = np.array([5000, 12000, 3500, 18000, 7000, 22000, 4500])

# 10,000 se zyada expenses filter karo.
high_exp = expenses[expenses > 10000]
print(high_exp)

# 5000 ya kam expenses identify karo.
low_exp = expenses[expenses > 500]
print(low_exp)
# np.where() se 10,000 se zyada expenses ko "Over Budget" aur baqi ko "Within Budget" label do.
result = np.where(expenses > 10000,'Over Budget','Within Budget')
print(result)

[12000 18000 22000]
[ 5000 12000  3500 18000  7000 22000  4500]
['Within Budget' 'Over Budget' 'Within Budget' 'Over Budget'
 'Within Budget' 'Over Budget' 'Within Budget']


In [14]:
# City-wise Sales
# Har row ek city ki aur har column ek month ki sales represent karta hai.
sales = np.array([
    [12000, 15000, 9000],
    [8000, 22000, 18000],
    [25000, 30000, 27000],
    [5000, 7000, 6000]
])
# 20,000 ya zyada sales filter karo.
high_sales = sales[sales > 20000]
print(high_sales)
# np.where() se sales 15,000 ya zyada hon to "Good Sales" aur baqi ko "Low Sales" label do.
sales_review = np.where(sales > 15000,'Good Sales','Low Sales')
print(sales_review)
# Sirf third city ki sales mein se 25,000 ya zyada values select karo.
high_sales = sales[2][sales[2] > 20000]
print(high_sales)

[22000 25000 30000 27000]
[['Low Sales' 'Low Sales' 'Low Sales']
 ['Low Sales' 'Good Sales' 'Good Sales']
 ['Good Sales' 'Good Sales' 'Good Sales']
 ['Low Sales' 'Low Sales' 'Low Sales']]
[25000 30000 27000]
